# Generated by Django 4.0.3 on 2022-04-05 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Crud', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='Card_account',
        ),
    ]
